language: python
python:
  - 3.6
env:
 - SQLALCHEMY_DATABASE_URI='' # TODO: Fix once TravisCI secrets are configured
install: 
  - pip install -r requirements.txt
script: 
  - flake8 etl ml dashboard
  - pytest
  - pytest --cov=./
after_success:
  - codecov --token 54bae0d6-e9bd-4bb9-b926-875f5cc023f2